### ISSUE TITLE
Can't get data from mqtt to show up in SignalK

### ISSUE THREAD

**Issue by Sparhawk76** [iuriaranda/signalk-mqtt-bridge#2]
I have successfully gotten the plugin to  respond to R requests, and publish SignalK data to my mqtt instance. 
If it makes any difference, I am running OpenPlotter v3 on a pi4b4Gb. 

I am now trying to get data from mqtt to show up in my SignalK.  From my understanding if I do:
mosquitto_pub -u <username> -P <passwd> -m '1' -t 'D/signalk/3160XXXXX/vessels/self/environment/test'

I should be able to see an entry in the data browser of SignalK environment.test with a value of 1, source being the bridge plugin ... however nothing shows up in SignalK.

Ultimately I am trying to get data into SignalK from my Renogy solar controllers, using https://github.com/Olen/solar-monitor  to get data from my controllers, and have configured it to use the prefix of 'D/signalk/3160XXXXX/vessels/self/renogy'  for its mqtt topic so I get a renogy data tree in SignalK, but of course its not showing up.  

This data shows up as expected in the mqtt explorer program I am using to debug, as does my test above, and my tests trying to set D/signalk/3160XXXXX/vessels/self/environment/wind/speedApparent as per your documentation. None of this changed anything in the data browser of SignalK

Am I doing something wrong or is this a bug?  Is there a better way of getting data from mqtt into SignalK (maybe node-red?).

**Comment by iuriaranda** [comment]
That's a mistake in the documentation. You should use `W/...` instead of `D/...` to write data into SignalK. Thanks for caching that. I'll update the documentation.

Let me know if it works properly with that change.

**Comment by Sparhawk76** [comment]
Thanks for the reply,  since the message I've used node-red to accomplish getting the data I want into signalk.  Glad to know it wasn't me doing something wrong though.

**Comment by iuriaranda** [comment]
Ok, I'll close this issue then.
