### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by aviatorhh** [iuriaranda/signalk-mqtt-bridge#8]
While your victron approach is quite nice, I am struggling to get the systemId of my SK installation. Please update your docs to help on this. Thanks

**Comment by iuriaranda** [comment]
The systemid is advertised in multiple places. The plugin publishes an MQTT message with the topic `N/signalk/<systemId>/system/Serial` and the systemid as payload. If you monitor the MQTT broker with something like the MQTT browser or similar you should see that message and get the system id.

Alternatively, the systemid is also displayed in the plugin settings section, above the configuration options.

I'll see if I can update the readme to reflect this in a meaningful way
